# Generated by Django 4.1.7 on 2023-04-02 05:34

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_activity_options_mentalhealthresource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='user',
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=wagtail.fields.RichTextField(max_length=3600, null=True, verbose_name='Activity Description'),
        ),
    ]
