# Generated by Django 4.1.7 on 2023-04-02 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_useractivity_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='date',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='isShared',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='is_recommended',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='likes',
        ),
    ]
