# Generated by Django 4.1.7 on 2023-04-02 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_useractivity_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentalhealthresource',
            name='description',
        ),
        migrations.RemoveField(
            model_name='mentalhealthresource',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='mentalhealthresource',
            name='resource_type',
        ),
    ]
