# Generated by Django 4.1.7 on 2023-04-02 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_mentalhealthresource_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MentalHealthResource',
        ),
    ]
