# Generated by Django 4.1.7 on 2023-04-02 05:46

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('home', '0007_delete_mentalhealthresource'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentalHealthResource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', wagtail.fields.StreamField([('content', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(form_classname='Title')), ('description', wagtail.blocks.RichTextBlock(form_classname='Description'))]))], use_json_field=None)),
                ('logo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mental_health_resource_logo', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
