# Generated by Django 4.1.7 on 2023-04-07 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('home', '0008_mentalhealthresource'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHub',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
                ('activity_id', models.IntegerField(blank=True, null=True)),
                ('mood', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('photos', models.ManyToManyField(blank=True, null=True, related_name='user_hub_photos', to='wagtailimages.image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Hub',
                'verbose_name_plural': 'User Hub',
            },
        ),
        migrations.RemoveField(
            model_name='userassessment',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='userassessment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userfavouriteactivity',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='userfavouriteactivity',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usermood',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userselfreflection',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='userselfreflection',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserActivity',
        ),
        migrations.DeleteModel(
            name='UserAssessment',
        ),
        migrations.DeleteModel(
            name='UserFavouriteActivity',
        ),
        migrations.DeleteModel(
            name='UserMood',
        ),
        migrations.DeleteModel(
            name='UserSelfReflection',
        ),
    ]
