# Generated by Django 4.1.7 on 2023-04-10 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_userhub_remove_userassessment_assessment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhub',
            name='type',
            field=models.CharField(default='reflection', max_length=50),
            preserve_default=False,
        ),
    ]
