# Generated by Django 4.1.7 on 2023-04-10 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_userhub_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhub',
            name='likes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_hub_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userhub',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_hub_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
