# Generated by Django 4.1.7 on 2023-04-13 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_userhub_likes_userhub_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthquestion',
            name='assessment',
        ),
        migrations.DeleteModel(
            name='HealthAssessment',
        ),
        migrations.DeleteModel(
            name='HealthQuestion',
        ),
    ]
