# Generated by Django 4.1.7 on 2023-04-13 23:55

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_healthassessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthassessment',
            name='instructions',
            field=wagtail.fields.RichTextField(max_length=3600, null=True, verbose_name='Instructions'),
        ),
    ]
